// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFRsFc5EvFNBYHZHikY_uroMJVxjdDVY',
    appId: '1:736551120280:web:85f00d2dbcad7995f04fed',
    messagingSenderId: '736551120280',
    projectId: 'flutter-test-1-c2ae1',
    authDomain: 'flutter-test-1-c2ae1.firebaseapp.com',
    storageBucket: 'flutter-test-1-c2ae1.appspot.com',
    measurementId: 'G-K6YKTJH080',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_IxKYJIzjY8-9tfF-8hMbS5HSzxis6xA',
    appId: '1:736551120280:android:180be489d17448d6f04fed',
    messagingSenderId: '736551120280',
    projectId: 'flutter-test-1-c2ae1',
    storageBucket: 'flutter-test-1-c2ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZtppNK2aN-5X1PsdLVSOQ9LfY5llyM7A',
    appId: '1:736551120280:ios:8249d2215bdbe1fef04fed',
    messagingSenderId: '736551120280',
    projectId: 'flutter-test-1-c2ae1',
    storageBucket: 'flutter-test-1-c2ae1.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZtppNK2aN-5X1PsdLVSOQ9LfY5llyM7A',
    appId: '1:736551120280:ios:4ee206733b9a88e1f04fed',
    messagingSenderId: '736551120280',
    projectId: 'flutter-test-1-c2ae1',
    storageBucket: 'flutter-test-1-c2ae1.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
